package com.usql.jdbc;

import com.usql.USqlCompiler;
import com.usql.dialect.Dialect;

import java.sql.*;

/**
 * JDBC Statement wrapper that compiles SQL through USQL before execution.
 */
public class USqlStatement implements Statement {

    private final Statement real;
    private final Dialect dialect;
    private final USqlCompiler compiler;

    USqlStatement(Statement real, Dialect dialect, USqlCompiler compiler) {
        this.real = real;
        this.dialect = dialect;
        this.compiler = compiler;
    }

    /** Compile U-SQL to the target dialect. */
    private String compile(String sql) throws SQLException {
        var result = compiler.compile(sql, dialect);
        if (!result.isSuccess()) throw new SQLException("USQL compile error: " + result.report());
        return result.getSql();
    }

    @Override public ResultSet executeQuery(String sql) throws SQLException { return real.executeQuery(compile(sql)); }
    @Override public int executeUpdate(String sql) throws SQLException { return real.executeUpdate(compile(sql)); }
    @Override public boolean execute(String sql) throws SQLException { return real.execute(compile(sql)); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return real.executeUpdate(compile(sql), autoGeneratedKeys); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return real.executeUpdate(compile(sql), columnIndexes); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return real.executeUpdate(compile(sql), columnNames); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return real.execute(compile(sql), autoGeneratedKeys); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return real.execute(compile(sql), columnIndexes); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return real.execute(compile(sql), columnNames); }

    @Override public void addBatch(String sql) throws SQLException { real.addBatch(compile(sql)); }
    @Override public void clearBatch() throws SQLException { real.clearBatch(); }

    @Override public void close() throws SQLException { real.close(); }
    @Override public int getMaxFieldSize() throws SQLException { return real.getMaxFieldSize(); }
    @Override public void setMaxFieldSize(int max) throws SQLException { real.setMaxFieldSize(max); }
    @Override public int getMaxRows() throws SQLException { return real.getMaxRows(); }
    @Override public void setMaxRows(int max) throws SQLException { real.setMaxRows(max); }
    @Override public void setEscapeProcessing(boolean enable) throws SQLException { real.setEscapeProcessing(enable); }
    @Override public int getQueryTimeout() throws SQLException { return real.getQueryTimeout(); }
    @Override public void setQueryTimeout(int seconds) throws SQLException { real.setQueryTimeout(seconds); }
    @Override public void cancel() throws SQLException { real.cancel(); }
    @Override public SQLWarning getWarnings() throws SQLException { return real.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { real.clearWarnings(); }
    @Override public void setCursorName(String name) throws SQLException { real.setCursorName(name); }
    @Override public ResultSet getResultSet() throws SQLException { return real.getResultSet(); }
    @Override public int getUpdateCount() throws SQLException { return real.getUpdateCount(); }
    @Override public boolean getMoreResults() throws SQLException { return real.getMoreResults(); }
    @Override public void setFetchDirection(int direction) throws SQLException { real.setFetchDirection(direction); }
    @Override public int getFetchDirection() throws SQLException { return real.getFetchDirection(); }
    @Override public void setFetchSize(int rows) throws SQLException { real.setFetchSize(rows); }
    @Override public int getFetchSize() throws SQLException { return real.getFetchSize(); }
    @Override public int getResultSetConcurrency() throws SQLException { return real.getResultSetConcurrency(); }
    @Override public int getResultSetType() throws SQLException { return real.getResultSetType(); }
    @Override public Connection getConnection() throws SQLException { return real.getConnection(); }
    @Override public boolean getMoreResults(int current) throws SQLException { return real.getMoreResults(current); }
    @Override public ResultSet getGeneratedKeys() throws SQLException { return real.getGeneratedKeys(); }
    @Override public int getResultSetHoldability() throws SQLException { return real.getResultSetHoldability(); }
    @Override public boolean isClosed() throws SQLException { return real.isClosed(); }
    @Override public void setPoolable(boolean poolable) throws SQLException { real.setPoolable(poolable); }
    @Override public boolean isPoolable() throws SQLException { return real.isPoolable(); }
    @Override public void closeOnCompletion() throws SQLException { real.closeOnCompletion(); }
    @Override public boolean isCloseOnCompletion() throws SQLException { return real.isCloseOnCompletion(); }
    @Override public int[] executeBatch() throws SQLException { return real.executeBatch(); }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return real.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return real.isWrapperFor(iface); }
}
